imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    # ...
    dbal:
        host:     localhost
        dbname:   YllyChatonsTest
        user:     root
        password: vandekadsye

lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/app/config/jwt/private-test.pem'
    public_key: '%kernel.project_dir%/app/config/jwt/public-test.pem'
    pass_phrase: "test"
    token_ttl: 3600